version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/log:/tmp/mongo
    command: mongod --logpath=/dev/null
  airnotifier:
    links:
      - mongodb
    depends_on:
      - mongodb
    build: .
    container_name: airnotifier
    volumes:
      - ./certs:/var/airnotifier/pemdir
      - ./logs:/var/log/airnotifier
    ports:
      - 8801:8801
    environment:
      - MONGO_USER=admin
      - MONGO_PASS=pass
      - MONGO_SERVER=mongodb
      - MONGO_PORT=27017
